name: test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.0
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5
  dio: ^5.4.3+1
  crypto: ^3.0.3
  path_provider: ^2.1.3
  routemaster: ^1.0.1
  appikorn_madix_widgets:
    git:
      url: "https://Appikorn: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@github.com/Appikorn/appikorn_madix_widgets.git"
  fpdart: ^1.1.0
  json_serializable: ^6.8.0
  flutter_secure_storage: ^9.2.2
  hooks_riverpod: ^2.5.1
  mockito: ^5.4.4

dependency_overrides:
  ffi: ^2.0.1
  intl: ^0.18.0
  flutter_svg: ^2.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/animations/
